ДЗ_4 ENUM
etretjakowa/Homework_OOP_vvedenie_1_2023 pull request #6
Opened 2023-04-11 11:36 UTC by etretjakowa

Проверьте, пожалуйста, ДЗ_5. Прошу обратить внимание:
1) насколько корректная реализация метода getType() в классах-наследниках?   
2) почему при выводе в консоль распечатывается по два раза инфо по энамам, если задавать в конструктор объекта параметр через getValueBus в объект bus и getValue в truck (при подаче параметра, например, в виде Truck.LoadCapacity.N2 такого не происходит). 
Буду очень благодарна обратной связи!

2023-04-11 18:35 UTC, OlgaLugacheva requested changes

2023-04-11 18:35 UTC, OlgaLugacheva commented on src/transport/Car.java
> +        }
достаточно было поле определить типа Type и его тут возвращать, а Type.CAR != Type.CAR это неверно

2023-04-11 18:35 UTC, OlgaLugacheva commented on src/transport/Bus.java
> +        if (Type.BUS != Type.BUS) {
см комментарий в предыдущем классе

2023-04-11 18:35 UTC, OlgaLugacheva commented on src/transport/Truck.java
> +        if (Type.TRUCK != Type.TRUCK) {
см комментарий в другом классе

2023-04-11 18:35 UTC, OlgaLugacheva commented on src/transport/Car.java
> +        System.out.println(Type.CAR);
вывод этот не нужен, скорее всего это, то что ты имела в виду под дублированием информации при выводе

2023-04-12 12:27 UTC, etretjakowa commented on src/transport/Car.java
> +        }
откорректирован

2023-04-12 12:27 UTC, etretjakowa commented on src/transport/Bus.java
> +        if (Type.BUS != Type.BUS) {
откорректирован

2023-04-12 12:27 UTC, etretjakowa commented on src/transport/Truck.java
> +        if (Type.TRUCK != Type.TRUCK) {
откорректирован

2023-04-12 12:28 UTC, etretjakowa commented on src/transport/Car.java
> +        System.out.println(Type.CAR);
откорректирован

2023-04-16 13:58 UTC, merged