ДЗ 7 коллекции List и Queue добавлены классы Mechanic и ServiceStation
etretjakowa/Homework_OOP_vvedenie_1_2023 pull request #8
Opened 2023-04-27 13:11 UTC by etretjakowa

2023-04-29 17:54 UTC, OlgaLugacheva requested changes

2023-04-29 17:54 UTC, OlgaLugacheva commented on src/transport/Main.java
> +        Truck truck1 = new Truck("Камаз", "1", 8.0, driverC1, Truck.LoadCapacity.getValue(10), mechanics);
по вопросу - вот здесь вызывается у enuma метод первый раз

2023-04-29 17:54 UTC, OlgaLugacheva commented on src/transport/Main.java
> +        Truck truck4 = new Truck("ТОНАР", "1", 9.8, driverC4, Truck.LoadCapacity.getValue(5), mechanics);
а здесь вызывается второй раз

чтобы не выводить в консоль лишнюю информацию, нужно тогда в энаме в Truck убрать из этого метода 
```
 public static LoadCapacity getValue(double value) {
            for (LoadCapacity e : LoadCapacity.values()) {
                if (value >= e.getMin() && value <= e.getMax()) {
                    System.out.println(e); //ВОТ ЭТУ СТРОКУ
                    return e;
                }
            }
            return null;
        }
```

2023-04-30 12:02 UTC, etretjakowa commented on src/transport/Main.java
> +        Truck truck4 = new Truck("ТОНАР", "1", 9.8, driverC4, Truck.LoadCapacity.getValue(5), mechanics);
Понятно, спасибо!

2023-05-01 13:38 UTC, merged